[package]
name = "parrot-rng"
version = "0.7.3"
edition = "2024"

description = "A lightweight, strictly deterministic procedural generation library for Rust"
authors = ["Dejaime de Oliveira <contact@dejai.me>"]
license = "MIT OR Apache-2.0 OR GPL-3.0-only OR LGPL-3.0-only"

repository = "https://github.com/dejaime/parrot"
documentation = "https://docs.rs/crate/parrot-rng/latest"
readme = "README.md"


categories = ["game-development", "simulation", "algorithms", "no-std"]
keywords = [
            "random", "rng", "simulation", "procedural", "gamedev"
        ]

[lib]
name = "parrot"
path = "src/lib.rs"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[profile.release]
lto = true
opt-level = "z"
panic = "abort"

[features]
default = []
std = []
rand-support = ["dep:rand_core"]
bevy-support = ["dep:bevy", "std"]
serde-support = ["dep:serde"]

[dependencies]
rand_core = { version = "0.6", optional = true, default-features = false }
bevy = { version = "0.17", optional = true, default-features = false, features = ["bevy_color"] }
serde = { version = "1.0", features = ["derive"], optional = true, default-features = false }

[dev-dependencies]
num_cpus = "1.16.0"
rand = { version = "0.8", features = ["small_rng"] }
criterion = "0.5"
serde_json = "1.0.145"

[[bench]]
name = "benchmark"
harness = false

[[bench]]
name = "multithreaded"
harness = false
