[package]
name = "parrot-rng"
version = "0.1.0"
edition = "2024"

description = "A very experimental crate for mod support in Bevy Game Engine games"
authors = ["Dejaime de Oliveira <contact@dejai.me>"]
license = "MIT OR Apache-2.0 (with or without LLVM-exception)"

homepage = "https://dejai.me/parrot-rng"
documentation = "https://dejai.me/parrot-rng/docs"
repository = "https://github.com/dejaime/parrot-rng"
readme = "README.md"


categories = ["game-development", "simulation", "algorithms", "mathematics", "no-std", "no-std::no-alloc"]
keywords = [
            "prng", "drng", "random-number-generator", "rng", "simulation", "procedural-generation",
            "cross-platform", "deterministic", "fixed-point"
        ]

[lib]
crate-type = ["rlib"]
name = "parrot"      # This allows 'use parrot::Parrot;'
path = "src/lib.rs"

[profile.release]
lto = true
opt-level = "z"
panic = "abort"

[dev-dependencies]
num_cpus = "1.16.0"